title: Site
sections:
  videos:
    label: Single-Channel Videos
    type: pages
    template: video
    image:
      cover: true
    layout: list
    size: small
    limit: 80
    sortBy: page.date asc
  expanded-media:
    label: Expanded Media
    type: pages
    template: expanded-media
    empty: "No expanded media yet"
    description: "Create a expanded media for the symposium. Each expanded media can have multiple presenters and specific details."
    image:
      cover: true
    layout: list
    limit: 80
  presentations:
    type: pages
    template: presentation
    empty: "No presentations yet"
    description: "Create a presentation for the symposium. Each presentation can have multiple presenters and specific details."
    image:
      cover: true
    layout: list
    limit: 80
    sortBy: page.date asc
  workshops:
    type: pages
    template: workshop
    empty: "No workshops yet"
    description: "Create a workshop for the symposium. Each workshop can have multiple presenters and specific details."
    image:
      cover: true
    layout: list
    limit: 80
    sortBy: page.date asc
  locations:
    type: pages
    template: location
    empty: "No locations yet"
    description: "Add locations for the symposium. Each location can have photos, descriptions, and map links."
    image:
      cover: true
      query: "page.photo.toFile"
    layout: cards
    size: small
    limit: 80
    sortBy: page.title asc
  presenters_info:
    label: Helpful Tip 🦄
    type: info
    text: "When you add an artist human, you will be asked for Title. This is <em>Page Title</em>, so use the presenter's full name, such as 'Lillian Schwartz'. It's a little odd, so I thought I'd mention it. - Rob
  presenters:
    label: Artist Humans
    type: pages
    template: presenter
    empty: "No humans yet"
    description: "Add an artist human for the symposium. Each human will have their own page with bio, photo, and social media links."
    image:
      cover: true
      query: "page.headshot.toFile"
    layout: list
    size: small
    limit: 100
    sortBy: page.presenter_name asc 
  pages:
    type: pages
    template: home
    empty: "No pages yet"
    image:
      cover: true
    layout: cards
    size: small
    limit: 20
    sortBy: page.title asc
